replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/frontend
  tag: v0.1.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer #ClusterIP
  port: 8080

resources: 
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi